# Generated by Django 4.2.6 on 2023-11-03 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_alter_job_options_jobapply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapply',
            old_name='link_url',
            new_name='linkedIn_url',
        ),
    ]
