# Generated by Django 4.2.6 on 2023-11-07 07:53

from django.db import migrations, models
import job.models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_rename_link_url_jobapply_linkedin_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='cover_letter',
            field=models.TextField(help_text='Add your cover letter here...', max_length=500),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='cv',
            field=models.FileField(help_text='Please upload your file here', upload_to='cv', validators=[job.models.validate_pdf_file]),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='githup_url',
            field=models.URLField(blank=True, help_text='Please enter your GitHub profile URL', null=True),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='linkedIn_url',
            field=models.URLField(blank=True, help_text='Please enter your LinkedIn profile URL', null=True),
        ),
    ]
